SATURN_MARK_COLOR="${SATURN_MARK_COLOR="%(?.green.red)"}"
SATURN_MARK_ICON_NORMAL="${SATURN_MARK_NORMAL_ICON="➜"}"
SATURN_MARK_ICON_ROOT="${SATURN_MARK_ROOT_ICON="❯"}"
SATURN_MARK_SEQUENCE="${SATURN_MARK_SEQUENCE="%(!.$SATURN_MARK_ICON_ROOT.$SATURN_MARK_ICON_NORMAL) "}"

saturn_mark() {
  printf %s "%F{$SATURN_MARK_COLOR}$SATURN_MARK_SEQUENCE%f"
}
