SATURN_PATH_COLOR="${SATURN_PATH_COLOR="blue"}"
SATURN_PATH_SEQUENCE="${SATURN_PATH_SEQUENCE="%~"}"
SATURN_PATH_ICON="${SATURN_PATH_ICON="🪐"}"

saturn_path() {
  printf %s "%F{$SATURN_PATH_COLOR}%B$SATURN_PATH_SEQUENCE $SATURN_PATH_ICON%b%f"
}
